-- ====================================================================
-- 1. ESTRUTURA DA TABELA (usuarios)
-- ====================================================================
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    tipo_usuario VARCHAR(50) NOT NULL,

    -- Campos embutidos de Endereco (@Embeddable)
    logradouro VARCHAR(255) NOT NULL,
    numero VARCHAR(50) NOT NULL,
    complemento VARCHAR(255),
    cidade VARCHAR(255) NOT NULL,
    estado VARCHAR(100) NOT NULL,
    cep VARCHAR(20) NOT NULL,

    data_ultima_alteracao DATE
    );

-- Inserção de Dono de Restaurante
INSERT INTO usuarios (
    nome, email, login, senha, tipo_usuario,
    logradouro, numero, complemento, cidade, estado, cep,
    data_ultima_alteracao
) VALUES (
             'Carlos Oliveira',
             'carlos.dono@restaurante.com',
             'carlos_dono',
             'senha123',
             'DONO_RESTAURANTE',
             'Rua das Flores',
             '100',
             'Bloco A, Sala 12',
             'São Paulo',
             'SP',
             '01234-567',
             '2026-07-28'
         );

-- Inserção de Cliente
INSERT INTO usuarios (
    nome, email, login, senha, tipo_usuario,
    logradouro, numero, complemento, cidade, estado, cep,
    data_ultima_alteracao
) VALUES (
             'Mariana Silva',
             'mariana.cliente@email.com',
             'mari_silva',
             'cliente123',
             'CLIENTE',
             'Avenida Central',
             '450',
             'Apto 32',
             'Campinas',
             'SP',
             '13010-000',
             '2026-07-28'
         );